contract_data = {
    'billing_number': 'test-123',
    'invoice_number': 'inv-123',
    'invoice_date': 'test/date/year',
    'client': 'test-cleint',
    'address_street': 'test-road',
    'address_line3': 'city-test, state-test, zip-test',
    'customer_number': 'test-client',
    'prime_contract_number': 'prime-123',
    'subcontractor_number': 'sub-123',
    'project_number': 'proj-123',
    'project_name': 'proj-test',
    'project_pop': 'test/date/start to test/date/end',
    'terms': 'test 30',
    'effective_pay_date': 'test/date/start',
    'due_date': 'test/date/end',
    'fee': 0,
    'rate': 145,
    'hours': 160,
    'job': 'Systems Architect (Test)',
    'employee_name': 'Kirkpatrick, Micah',
    'ts_date': 'test/date/again',
    'group_description': 'test',
    'billing_period_from': 'test/date/start',
    'billing_period_to': 'test/date/end',
}